### ISSUE TITLE
Payment Page Closing automatically

### ISSUE THREAD

**Issue by vidya-hub** [vkpdeveloper/payu_money_flutter#14]
I have done all the integration things with flutter,
but while opening the payment page it is automatically closing with a toast message like  " Some error Occured ".
Please help me !

**Comment by rohitrvayuz** [comment]
@vkpdeveloper

**Comment by vkpdeveloper** [comment]
Dear currently I am finding someone who can contribute and maintain these projects.

**Comment by vidya-hub** [comment]
I fixed this issue by giving correct credentials in php server like merchant key and salt 

I got the correct hash value.
Now the payment thing was working

So please check your credentials before deploying the php server globally 

Because the payment thing was working perfectly ☺️

Thanks for the package 👍.

**Comment by vkpdeveloper** [comment]
I am happy that it worked but if somebody wants to be a maintainer or wants to contribute to the package, please confirm.
